### ISSUE TITLE
Couple of new plugins

### ISSUE THREAD

**Issue by iantasker** [spark-is-awesome/awesome-spark#18]
To complement our plugin of Spark-Roles ( https://github.com/zinethq/spark-roles || https://packagist.org/packages/zinethq/spark-roles ) which you have kindly included, we have also released the following plugins

- Spark Invite ( https://github.com/zinethq/spark-invite || https://packagist.org/packages/zinethq/spark-invite )
- Spark User Team Email ( https://github.com/zinethq/spark-user-team-email || https://packagist.org/packages/zinethq/spark-user-team-email )

**Comment by jpmurray** [comment]
Thank you, just added them!
