### ISSUE TITLE
Is this repo being maintained anymore?

### ISSUE THREAD

**Issue by sburkett** [spark-is-awesome/awesome-spark#24]
Last commit was quite a while ago, and there are a few pull requests in the queue. Happy to take it over if you don't have the time anymore or what not.

**Comment by Braunson** [comment]
@jpmurray Also happy to help maintain here.

**Comment by jpmurray** [comment]
Oh my.

I'm stilling maintaining it, I just relied on (non existent) Github notifications to keep my updated of PRs! Sorry guys!

**Comment by Braunson** [comment]
@jpmurray I hear ya, my own repo notifications get mixed in with the notifications of other repositories I follow, 10/10 times I never see my own notifications.
